#!/bin/bash

echo "------ HOOK START - BUILD -------"
printenv

# ENV VARs are set by the cloud.docker.com build process, and are available during automated builds, automated tests,
# and while executing hooks like here.
# DOCKER_TAG: the Docker repository tag being built.
# https://docs.docker.com/docker-hub/builds/advanced/

docker build \
--no-cache=true \
--build-arg \
BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
VCS_REF=$SOURCE_COMMIT \
-t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
